version: "3.9"

services:
  laravel_app:
    build:
      context: ../backend       # путь к коду проекта
      dockerfile: ../docker/laravel/Dockerfile  # путь к Dockerfile
    container_name: laravel_app
    volumes:
      - ../backend:/var/www/laravel
    command: php artisan serve --host=0.0.0.0 --port=9000
    depends_on:
      - laravel_db
    ports:
      - "9000:9000"

    

  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - laravel_db
    environment:
      PMA_HOST: laravel_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  vue_frontend:
    image: node:24
    container_name: vue_frontend
    working_dir: /var/www/frontend
    volumes:
      - ../frontend:/var/www/frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    depends_on:
      - laravel_app

volumes:
  dbdata:
