version: "3.9"

services:
  laravel_app:
    build:
      context: ../backend
      dockerfile: ../docker/laravel/Dockerfile
    container_name: laravel_app
    volumes:
      - ../backend:/var/www/laravel:cached
    depends_on:
      - laravel_db
    networks:
      - app-network

  laravel_nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    depends_on:
      - laravel_app
      - vue_frontend   # nginx должен стартовать после фронта
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../backend:/var/www/laravel:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    networks:
      - app-network

  laravel_db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: GAtkw57{E–[a4Hd
      MYSQL_ROOT_PASSWORD: 3#OeGt%9n\EC3v?
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - laravel_db
    environment:
      PMA_HOST: laravel_db
      MYSQL_ROOT_PASSWORD: 3#OeGt%9n\EC3v?
    volumes:
      - "8080:80"
    networks:
      - app-network

  vue_frontend:
    image: node:24
    container_name: vue_frontend
    working_dir: /var/www/frontend
    volumes:
      - ../frontend:/var/www/frontend:cached
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
